### ISSUE TITLE
All files in Nova switched to HTML (Liquid) Syntax

### ISSUE THREAD

**Issue by hello-jeff** [arthrfrts/Liquid.novaextension#2]
While working on another project that doesn't use Liquid, the syntax coloring on all files went away as if I mistyped something somewhere. After testing a few other projects and finding the same issue with syntax coloring, I noticed that all my files had been switched to HTML (Liquid). I deactivated the extension and everything went back to normal, all files were set to their proper syntax. This happened with Nova open and one project running. I didn't change anything in preferences.

I just reactivated the extension, restarted Nova, and everything switch to HTML (Liquid). Any ideas?

**Comment by arthrfrts** [comment]
Hmm, this may be related to #1.

Did your general HTML files switched to HTML (Liquid), or all files are switching to it? I've been dealing with some SCSS and haven't seen this behavior in my setup.

**Comment by hello-jeff** [comment]
It isn't affecting CSS files. I think it's just HTML. I've mainly been working with PHP-HTML files (WordPress sites). The funny thing is that if I disable the extension and reboot Nova, everything returns to normal. If I enable the extension, reboot Nova, reopen the project, all open files are fine but if I open a new file, it opens as HTML Liquid.

**Comment by arthrfrts** [comment]
Yeah, this should be happening since the detector changed in v1.0.2, specially for HTML files that use similar handlebars like Twig and Nujunks.

I'll look into making this detector condition less intrusive, if you want to keep the extension enabled while I do this, you can always change the active syntax highlighter in the command palette (`Cmd + P`).

**Comment by hello-jeff** [comment]
Thank you for looking into it and the suggestion. I work a lot with Liquid for Shopify sites and love the extension.

**Comment by arthrfrts** [comment]
Ok! I *think* I found a way for the HTML detector to be less intrusive and just published v1.0.3. Let me know what you think!

**Comment by hello-jeff** [comment]
So far, so good! The update seems to take care of the problem. I'll be switching back and forth frequently between Liquid and non-Liquid projects all next week so I'll keep you posted if anything pops up. Thank you so much for making the extension and fixing the bug so quickly.

**Comment by arthrfrts** [comment]
Thank you for reporting it! I also added code completions on it last night, since I had to fix this issue as well. Let me know if there's anything else I can improve!
