### ISSUE TITLE
css/scss.liquid files

### ISSUE THREAD

**Issue by hello-jeff** [arthrfrts/Liquid.novaextension#3]
Any chance there will be an update soon with formatting for CSS and/or SCSS liquid files?

**Comment by arthrfrts** [comment]
I never used Liquid tags on `.scss` files, but I will certainly try! Can you give me a Liquid+Sass file for me to try some things over this weekend?

And sorry for this late response! I'm not around my personal computer this past month, but things are changing over the weekend.

**Comment by hello-jeff** [comment]
No problem on the delay. Thank you so much for following up!

Just emailed you links to two CSS files, one is a huge css.liquid file that my theme uses for its main stylesheet.

**Comment by arthrfrts** [comment]
Just released v1.2, which adds support for Liquid on CSS and on SCSS files. I can't figure out how to make Nova auto-detect Liquid tags in those files, so you'll have to select `CSS (Liquid)` or `SCSS (Liquid)` in the Editor Syntax selector.

**Comment by hello-jeff** [comment]
Just checked it out and it works like a charm! Thank you so much for updating so quickly.

Also, even though I wouldn't mind manually switching to the liquid versions in the editor syntax, it automatically recognized it on mine. I opened up several css.liquid files and they were all recognized. I didn't have to do anything.

**Comment by arthrfrts** [comment]
Ah, good to know! The examples I've used here weren't automatically recognized (as well as the new `Markdown (Liquid)`), so I wonder how can I make this work better in the future. Meanwhile I'm closing this issue, but please feel free to report new bugs or suggest new features! I promise I'll not take so long to respond.
