### ISSUE TITLE
Markdown Highlighting

### ISSUE THREAD

**Issue by BryanSchuetz** [arthrfrts/Liquid.novaextension#5]
Would be good if we could get Highlighting for Markdown front matter sections (for Jekyll, etc.) within files set to the HTML (Liquid) syntax.

**Comment by BryanSchuetz** [comment]
Maybe this is something that has to bee added to the Markdown syntax xml—using Content Match Detectors?

https://docs.nova.app/syntax-reference/syntaxes/#content-match-detectors

**Comment by arthrfrts** [comment]
Sorry for the belated response! I'm not around my Mac right now, but I'll look it this next Saturday and try some things, for sure! I think I can do something similar with #3.

**Comment by arthrfrts** [comment]
Just released v1.2 with a new `Markdown (Liquid)` syntax, which highlights Liquid syntax in your Markdown files. There are still two issues:

1. For some reason, I can't find a way for Nova to detect Liquid tags and variables to choose the proper syntax automatically like it happens with `HTML (Liquid)`, so you need to choose `Markdown (Liquid)` manually in your Editor Syntax selector.
2. I also can't figure it out how to prevent Nova from interpreting 4 spaces tabbing as a Markdown code, which prevents Liquid highlighting.

I'll look into these issues to release a fix whenever I can, but if you manage to find out how to, I would love some help!

**Comment by BryanSchuetz** [comment]
Awesome. Will take a look at the other issues.

**Comment by BryanSchuetz** [comment]
Yeah, I've added in detectors for filetypes and opening tags and still doesn't seem to work. What's more—I can't seem to get some other extensions to extend to `liquid-markdown` as a syntax. (specifically the  tailwind, and emmet extensions). Not sure what the problem is.

**Comment by BryanSchuetz** [comment]
err...actually I take that back, sorry! Was able to get them to extend to both `liquid-html` and `liquid-markdown`.

**Comment by arthrfrts** [comment]
Yay! You can create a PR with this fix if you want, I'd love to check what went wrong with my approach.
