### ISSUE TITLE
Update for Tree-Sitter

### ISSUE THREAD

**Issue by BryanSchuetz** [arthrfrts/Liquid.novaextension#6]
Is anyone working on updating this extension to work with the new tree-sitter implementation for syntaxes in the  beta 10 version of Nova?

https://docs.nova.app/syntax-reference/tree-sitter/

**Comment by arthrfrts** [comment]
Sorry, I'm not, at least not right now. Would love some help if you can! :)

**Comment by arthrfrts** [comment]
Dropping this here for whenever I get the time: https://github.com/Shopify/tree-sitter-liquid-ii

**Comment by BryanSchuetz** [comment]
👆 That should make things easier.

**Comment by arthrfrts** [comment]
I'm starting to work on this. Looking to release a v2.0 reworking the extension from the ground up.

I still don't understand much about tree sitter, so if anyone can help me, it's appreciated!

**Comment by arthrfrts** [comment]
A brief update on this, after months struggling to create a working tree-sitter syntax for Liquid, I'm following the development of [@hankthetank27's own `tree-sitter-liquid`](https://github.com/hankthetank27/tree-sitter-liquid).

I created an issue to track (or fix my implementation of) highlighting filters and `objects.parameters`: https://github.com/hankthetank27/tree-sitter-liquid/issues/3
