### ISSUE TITLE
When Liquid 1.2.4 is installed and active, gutter/inline Color Previews no longer appear when editing HTML

### ISSUE THREAD

**Issue by scritturamista** [arthrfrts/Liquid.novaextension#7]
If you open an HTML document while Liquid is active, the editor no longer displays Color Previews inline or in the gutter.
This has been reproduced with Nova 11.4 and later, on macOS Sonoma 14, and Liquid 1.2.4.

**Comment by arthrfrts** [comment]
This one is odd. I'm trying to activate color previews with other syntaxes based on HTML (EJS, for example) and they don't provide this feature as well. I'm investigating if this is a limitation of XML-based language definitions.

**Comment by arthrfrts** [comment]
It seems that some XML language features got removed on newer versions of Nova. I'm going to reimplement the HTML syntax as XML in the next release, it may fix this.
